//> using scala 3.7.4
//> using toolkit 0.7.0
//> using dep org.apache.commons:commons-digester3:3.2
//> using dep org.apache.commons:commons-math4-core:4.0-beta1
//> using dep org.apache.commons:commons-numbers-primes:1.2
//> using dep com.google.guava:guava:33.1.0-jre
//> using dep commons-codec:commons-codec:1.19.0
//> using dep org.scala-graph:graph-core_2.13:2.0.3
//> using dep org.scala-lang.modules::scala-parallel-collections:1.2.0
//> using dep org.scala-lang.modules::scala-collection-contrib:0.4.0
